### PR TITLE
Remove g++ flag

### PR DESCRIPTION
**Pull request by lboklin**
Just trimming it down a bit

### CODE REVIEW

**Comment by krakrjak** [comment]
I like the first commit here. The tidying up of the weston derivations are a welcome addition. As for the removal of g++ as the linker in the stack.yaml file, I am less certain. To be sure that change actually works, you must perform a clean build (from scratch with no partial build artifacts). I have had issues where I thought I could live without the g++ linker as well, but they turned out to be apparitions.

**Comment by lboklin** [comment]
I've successfully built after I cleaned all and any artifacts I could find, but I'll do a double/triple check to make sure. To clean everything I have a script with:
```
find . -name ".stack-work" -type d -exec rm -r {} + 2>/dev/null
stack --nix clean
stack --nix-pure build --fast
```

**Comment by krakrjak** [comment]
Hrm... Ok, I will double check this myself this evening (about 5 hours from now). The issue is likely that when linking to `OpenVR` there are C++ symbols needed and that linking is not happening in the nix build ATM. I will add more information here as soon as I can dig up my notes and test the build also.

**Comment by lboklin** [comment]
I'll keep this for the g++ removal because of the ongoing discussion and create a separate PR for the nix stuff.

**Comment by lboklin** [comment]
Another clean rebuild of the project succeeded, but I do get [warnings from c2hs](http://lpaste.net/362302).

**Comment by lboklin** [comment]
Tested on Ubuntu 18.04 and it doesn't work. Closing.

**Pull request closed without merging**
